### ISSUE TITLE
prisma-select issue for custom output path

### ISSUE THREAD

**Issue by manarjan** [paljs/prisma-tools#210]
I am getting the below error when I try to use 

`const select = new PrismaSelect(info).value;`

> [Nest] 65877   - 17/05/2021, 16:45:13   [ExceptionsHandler] Cannot find module '.prisma/client'

My PrismaClient is in a custom path rather than the default, as I am using a monorepo for multiple microservices.

```
generator client {
    provider      = "prisma-client-js"
    binaryTargets = ["native", "darwin"]
    output        = "../src/.generated/prisma/client"
}
```
Is there a way to point PrismaSelect to the correct Client?

**Comment by AhmedElywa** [comment]
`Import {Prisma} from "../generate/client"`

and 

const select = new PrismaSelect(info, {dmmf:Prisma.dmmf}).value;

**Comment by manarjan** [comment]
@AhmedElywa thanks for the quick response.

I was able to make it work, although with a slight modification.

``` const select = new PrismaSelect(info, { dmmf: [Prisma.dmmf] }).value;```

had to pass the dmmf in an array.

**Comment by woss** [comment]
i have to reopen this issue. it doesn't work with the latest versions of this project and prisma (5)

**Comment by AhmedElywa** [comment]
It's Prisma.dmmf, not DMMF

**Comment by woss** [comment]
Hi, indeed it is. So i ended up passing the `Prisma.dmmf as Prisma.Document` because of the type errors. Now it works as it should. 



<img width="365" alt="image" src="https://github.com/user-attachments/assets/8a6410cd-d4eb-42ad-a196-cd6836f45312">
<img width="884" alt="image" src="https://github.com/user-attachments/assets/3643bd7f-972c-4314-8d8f-bbb33410ba10">
